### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by OldFatBoy** [CuteLeon/DeviceMonitor#1]
大神，请教一下，您使用HOOK是监听Windows哪个模块，是pnp管理器，还是事件通知。
我现在想做一个程序，想要实现的功能是，当USB设备插入时，获取USB的信息，并暂时中断USB挂载，将获取的USB信息和后台数据库中的数据对比，如果是白名单内的设备就返回同意挂载，如果不是则返回，程序根据后台的消息做出相应的反应。
因为一直做Linux开发，所以在Windows上没有实现思路，请大神指点一二。

**Comment by CuteLeon** [comment]
不好意思，您所说得拦截挂载功能，我也不太了解，因为程序HOOK到的消息是系统挂载优盘和移除优盘之后发送过来的。但是有一个思路：接收到优盘挂载消息之后获取优盘的指纹，如果指纹不匹配，立即使用API把优盘移除掉，这个算法不太严谨。
